from enum import Enum


class AppModes(Enum):
    ARMED = 0
    REQUEST_DISARM = 1
    DISARMED = 2
    REQUEST_PASSWORD_CHANGE = 3
    REQUEST_NEW_PASSWORD_1 = 4
    REQUEST_NEW_PASSWORD_2 = 5
    NEW_PASSWORDS_DONT_MATCH = 6
    PASSWORD_CHANGED = 7
    INCORRECT_PASSWORD = 8
